src/ipssihelp/ipssihelp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('worker.urls', namespace='worker')),
]

src/ipssihelp/worker/urls.py
from django.urls import re_path, path
from . import views

app_name = 'worker'

urlpatterns = [
    re_path('^$', views.home, name='home'),
    re_path('supply', views.supply, name='supply'),
    re_path('demand', views.demand, name='demand'), 
    re_path(r'detail/(?P<id>[\w-]+)/$', views.detail, name='detail'), 
    path('account/signup/', views.signup, name='signup'),
    path('account/login/', views.login_view, name='login_view'),
    path('account/logout/', views.logout_view, name='logout_view'),
    path('account/profil/', views.profil, name='profil'),
    path('account/announces/', views.announces, name='announces'),
    path('account/announces/add', views.add_announce, name='add_announce'),
    re_path(r'conversation/(?P<id>[\w-]+)/$', views.conversation, name='conversation'),


]

src/ipssihelp/worker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Ad, Category, Message, Conversation


class ConversationForm(forms.Form):
    class Meta:
        model = Conversation


class ProfilForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')



class SignupForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    
    def __init__(self, *args, **kwargs):
        super(SignupForm,self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control'
        })


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2',)

TYPE_CHOICES = [
    ('supply', 'Offre'),
    ('demand', 'Demande'),
]

class AnnouncesForm(forms.Form):
    title = forms.CharField(required=True)
    description = forms.CharField(widget=forms.Textarea,required=True)
    category = forms.ModelChoiceField(queryset=Category.objects.all())
    type = forms.CharField(
        required=True,
        widget=forms.Select(choices=TYPE_CHOICES),
    )

    def __init__(self, *args, **kwargs):
        super(AnnouncesForm,self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['description'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['category'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['type'].widget.attrs.update({
            'class': 'form-control'
        })


    class Meta:
        model = Ad
        fields = ('title', 'description', 'category', 'type',)


class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),)


    def __init__(self, *args, **kwargs):
        super(LoginForm,self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control'
        })


    class Meta:
        model = Ad
        fields = ('title', 'description', 'category', 'type',)

class MessageForm(forms.ModelForm):
    content = forms.CharField(required=True, widget=forms.Textarea)


    class Meta:
        model = Message
        fields = ('content',)

src/ipssihelp/worker/views.py
from django.contrib.auth import get_user, decorators, authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Ad, User, Conversation, Message
from .forms import ConversationForm
from django.views.decorators.csrf import csrf_protect, requires_csrf_token
from .forms import SignupForm, ProfilForm, AnnouncesForm, LoginForm, MessageForm
from django.db.models import Count

def home(request):
    template = loader.get_template('home.html')
    context = {
        "topFive" : User.objects.annotate(num_ads=Count('ad')).order_by('-num_ads')[:5],
        "lastDemand" : Ad.objects.filter(type = 'demand',status= 'online' ).order_by('id')[:5],
        "lastSupply" : Ad.objects.filter(type = 'supply',status= 'online' ).order_by('id')[:5]

    }
    return HttpResponse(template.render(context,request))



def supply(request):
    template = loader.get_template('ad/supply.html')
    result =  Ad.objects.filter(type = 'supply')
    search_term = ''
    if 'search' in request.GET:
        search_term = request.GET['search']
        result = Ad.objects.all().filter(title__contains=search_term, type='supply') 

    context = {
        "ads": result
    }
    return HttpResponse(template.render(context,request))


def demand(request):
    template = loader.get_template('ad/demand.html')
    result =  Ad.objects.filter(type = 'demand')

    search_term = ''
    if 'search' in request.GET:
        search_term = request.GET['search']
        result = Ad.objects.all().filter(title__contains=search_term, type='demand') 

    context = {
        "ads": result
    }
    return HttpResponse(template.render(context,request))


def detail(request, id):

    template = loader.get_template('ad/detail.html')
    idAd = int(id)
    form = ConversationForm()
    if request.method == 'POST':
        form = ConversationForm(request.POST)
        ad = Ad.objects.get(id=idAd)
        conversation = Conversation.objects.create(ad=ad)
        if form.is_valid():
            conversation.save()
            return redirect('worker:conversation', id=conversation.id)

    try:
        context = {
            "ad":  Ad.objects.get(id = idAd)
        }
    except:
        context = {
            "ad":  None
        }

    if request.method == 'POST':
        form = ConversationForm(request.POST)
        if form.is_valid():
            return HttpResponse(template.render(context,request))

    


    return HttpResponse(template.render(context,request))


@csrf_protect
@requires_csrf_token
def signup(request):
    template = loader.get_template('accounts/signup.html')

    user = get_user(request)
    if not user.is_authenticated:
        if request.method == 'POST':
            form = SignupForm(request.POST)
            context = {
                'form': form
            }
            if form.is_valid():
                form.save()
                email = form.cleaned_data['email']
                raw_password = form.cleaned_data['password1']
                user = authenticate(email=email, password=raw_password)
                login(request, user)
                return redirect('worker:home')
        else:
            form = SignupForm()
            context = {
                'form': form
            }

        return HttpResponse(template.render(context, request))

    return redirect('worker:home')


@decorators.login_required(login_url='/account/login/')
def profil(request):

    template = loader.get_template('accounts/profil.html')
    user = get_user(request)
    context = {
        "user":  user
    }
    if request.method == 'POST':
            form = ProfilForm(request.POST)
            context = {
                'form': form
            }
            if form.is_valid():
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.email = form.cleaned_data['email']
                user.save()

           
    else:
        form = ProfilForm(initial={'email': user.email, 'first_name' : user.first_name, 'last_name': user.last_name})
        context = {
            'form': form
        }
    return HttpResponse(template.render(context,request))

@decorators.login_required(login_url='/account/login/')
def announces(request):

    template = loader.get_template('accounts/announces.html')
    user = get_user(request)
    context = {
        "announces":  Ad.objects.filter(user_id = user.id)
    }
 
    return HttpResponse(template.render(context,request))

@decorators.login_required(login_url='/account/login/')
def add_announce(request):

    template = loader.get_template('accounts/add.html')
    user = get_user(request)
    announces = Ad()
    context = {
        "announces":  Ad.objects.filter(user_id = user.id)
    }
    if request.method == 'POST':
            form = AnnouncesForm(request.POST)
            
            if form.is_valid():
                announces.title = form.cleaned_data['title']
                announces.description = form.cleaned_data['description']
                announces.category = form.cleaned_data['category']
                announces.type = form.cleaned_data['type']
                announces.status = "online"
                announces.user = user
                announces.save()
                context = {
                    'form': form,
                    'success': True
                }
           
    else:
        form = AnnouncesForm()
        context = {
            'form': form,
            'success': False
        }
    return HttpResponse(template.render(context,request))



def logout_view(request):
    logout(request)
    return redirect('worker:home')

def login_view(request):
    template = loader.get_template('accounts/login.html')
    user = get_user(request)
    if not user.is_authenticated:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            context= {
                'form': form
            }
            if form.is_valid():
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                user = authenticate(email=email, password=password)
                if user:
                    login(request,user,backend='django.contrib.auth.backends.ModelBackend')
                    return redirect('worker:home')
                else:
                    form = LoginForm()
                    context = {
                        'form' : form,
                        "error" : "Vos identifiants sont incorrects !"
                    }
                
        else:
            form = LoginForm()
            context= {
                'form': form
            }
        return HttpResponse(template.render(context,request))

    return redirect('worker:home')

    
@csrf_protect
@requires_csrf_token
def conversation(request, id):
    template = loader.get_template('ad/conversation.html')
    id = int(id)
    print(id)
    conversation = Conversation.objects.get(id=id)
    print(conversation)

    get_messages = Message.objects.filter(conversation_id=id).order_by('-created')
    form = MessageForm()
    message = Message()
    if request.method == 'POST':
        form = MessageForm(request.POST)
        user = get_user(request)
        message.sender = user
        message.conversation = conversation
        message.content = form.data["content"]
        if form.is_valid():
            message.save()
            context = {
                'conversation': conversation,
                'messages': get_messages,
                'form': form,
            }
            return HttpResponse(template.render(context, request))
    context = {
        'conversation': conversation,
        'messages': get_messages,
        'form': form,
    }
   
    return HttpResponse(template.render(context, request))

src/ipssihelp/worker/templates/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    {% block title %}
    <title>CovidAids</title>
    {% endblock %}

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">CovidAids</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'worker:demand' %}">Demande</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'worker:supply' %}">Offres</a>
                    </li>
                    
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'worker:profil' %}">{{ user.get_full_name }}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'worker:signup' %}">Inscription</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'worker:login_view' %}">Connexion</a>
                        </li>
                    {% endif %}
            
                </ul>
                {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link btn btn-warning" href="{% url 'worker:add_announce' %}">Ajouter Une Annonce</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'worker:logout_view' %}">Déconnexion</a>
                    </li>
                </ul>
                {% endif %}
            </div>
    </nav>
    {% block content %}
    {%endblock %}
  </body>
</html>

src/ipssihelp/worker/templates/home.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <h1 class="display-4">Bienvenue sur CovidAids !</h1>
  <p class="lead">
    Premier outils dedié au partage de service concernant le Covid-19
  </p>
  <hr class="my-4" />
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/demand" role="button"
      >Voir les demandes</a
    >
  </p>
</div>

<div class="container">
  <div>
    <h1>Top 5 Annonceurs</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Nom</th>
          <th scope="col">Prenom</th>
          <th scope="col">Nb Annonce</th>
        </tr>
      </thead>
      <tbody>
        {% for user in topFive %}

        <tr>
          <td>{{user.first_name}}</td>
          <td>{{user.last_name}}</td>
          <td>{{user.num_ads}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div>
    <h1>5 Dernieres demandes</h1>
    <div class="row row-cols-1 row-cols-md-3">
      {% for ad in lastDemand %}
      <div class="col mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
              <a href="{% url 'worker:detail' id=ad.id %}">{{ ad.title }}</a>
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ ad.user }}</h6>
            <p class="card-text">{{ ad.description }}</p>
            <a href="{% url 'worker:detail' id=ad.id %}" class="card-link"
              >En savoir plus</a
            >
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>

  <div>
    <h1>5 Dernieres Offres</h1>
    <div class="row row-cols-1 row-cols-md-3">
      {% for ad in lastSupply %}
      <div class="col mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
              <a href="{% url 'worker:detail' id=ad.id %}">{{ ad.title }}</a>
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ ad.user }}</h6>
            <p class="card-text">{{ ad.description }}</p>
            <a href="{% url 'worker:detail' id=ad.id %}" class="card-link"
              >En savoir plus</a
            >
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}