src/ipssihelp/ipssihelp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('worker.urls', namespace='worker')),
]

src/ipssihelp/worker/urls.py
from django.urls import re_path, path
from . import views

app_name = 'worker'

urlpatterns = [
    re_path('^$', views.home, name='home'),
    re_path('supply', views.supply, name='supply'),
    re_path('demand', views.demand, name='demand'), 
    re_path(r'detail/(?P<id>[\w-]+)/$', views.detail, name='detail'), 
    path('account/signup/', views.signup, name='signup'),
    path('account/login/', views.login_view, name='login_view'),
    path('account/logout/', views.logout_view, name='logout_view'),
    path('account/profil/', views.profil, name='profil'),
    path('account/announces/', views.announces, name='announces'),
    path('account/announces/add', views.add_announce, name='add_announce'),
    re_path(r'conversation/(?P<id>[\w-]+)/$', views.conversation, name='conversation'),


]

src/ipssihelp/worker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Ad, Category, Message, Conversation


class ConversationForm(forms.Form):
    class Meta:
        model = Conversation


class ProfilForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')



class SignupForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    
    def __init__(self, *args, **kwargs):
        super(SignupForm,self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control'
        })


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2',)

TYPE_CHOICES = [
    ('supply', 'Offre'),
    ('demand', 'Demande'),
]

class AnnouncesForm(forms.Form):
    title = forms.CharField(required=True)
    description = forms.CharField(widget=forms.Textarea,required=True)
    category = forms.ModelChoiceField(queryset=Category.objects.all())
    type = forms.CharField(
        required=True,
        widget=forms.Select(choices=TYPE_CHOICES),
    )

    def __init__(self, *args, **kwargs):
        super(AnnouncesForm,self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['description'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['category'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['type'].widget.attrs.update({
            'class': 'form-control'
        })


    class Meta:
        model = Ad
        fields = ('title', 'description', 'category', 'type',)


class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),)


    def __init__(self, *args, **kwargs):
        super(LoginForm,self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control'
        })


    class Meta:
        model = Ad
        fields = ('title', 'description', 'category', 'type',)

class MessageForm(forms.ModelForm):
    content = forms.CharField(required=True, widget=forms.Textarea)


    class Meta:
        model = Message
        fields = ('content',)

src/ipssihelp/worker/views.py
from django.contrib.auth import get_user, decorators, authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Ad, User, Conversation, Message
from .forms import ConversationForm
from django.views.decorators.csrf import csrf_protect, requires_csrf_token
from .forms import SignupForm, ProfilForm, AnnouncesForm, LoginForm, MessageForm
from django.db.models import Count

def home(request):
    template = loader.get_template('home.html')
    context = {
        "topFive" : User.objects.annotate(num_ads=Count('ad')).order_by('-num_ads')[:5],
        "lastDemand" : Ad.objects.filter(type = 'demand',status= 'online' ).order_by('id')[:5],
        "lastSupply" : Ad.objects.filter(type = 'supply',status= 'online' ).order_by('id')[:5]

    }
    return HttpResponse(template.render(context,request))



def supply(request):
    template = loader.get_template('ad/supply.html')
    result =  Ad.objects.filter(type = 'supply')
    search_term = ''
    if 'search' in request.GET:
        search_term = request.GET['search']
        result = Ad.objects.all().filter(title__contains=search_term, type='supply') 

    context = {
        "ads": result
    }
    return HttpResponse(template.render(context,request))


def demand(request):
    template = loader.get_template('ad/demand.html')
    result =  Ad.objects.filter(type = 'demand')

    search_term = ''
    if 'search' in request.GET:
        search_term = request.GET['search']
        result = Ad.objects.all().filter(title__contains=search_term, type='demand') 

    context = {
        "ads": result
    }
    return HttpResponse(template.render(context,request))


def detail(request, id):

    template = loader.get_template('ad/detail.html')
    idAd = int(id)
    form = ConversationForm()
    if request.method == 'POST':
        form = ConversationForm(request.POST)
        ad = Ad.objects.get(id=idAd)
        conversation = Conversation.objects.create(ad=ad)
        if form.is_valid():
            conversation.save()
            return redirect('worker:conversation', id=conversation.id)

    try:
        context = {
            "ad":  Ad.objects.get(id = idAd)
        }
    except:
        context = {
            "ad":  None
        }

    if request.method == 'POST':
        form = ConversationForm(request.POST)
        if form.is_valid():
            return HttpResponse(template.render(context,request))

    


    return HttpResponse(template.render(context,request))


@csrf_protect
@requires_csrf_token
def signup(request):
    template = loader.get_template('accounts/signup.html')

    user = get_user(request)
    if not user.is_authenticated:
        if request.method == 'POST':
            form = SignupForm(request.POST)
            context = {
                'form': form
            }
            if form.is_valid():
                form.save()
                email = form.cleaned_data['email']
                raw_password = form.cleaned_data['password1']
                user = authenticate(email=email, password=raw_password)
                login(request, user)
                return redirect('worker:home')
        else:
            form = SignupForm()
            context = {
                'form': form
            }

        return HttpResponse(template.render(context, request))

    return redirect('worker:home')


@decorators.login_required(login_url='/account/login/')
def profil(request):

    template = loader.get_template('accounts/profil.html')
    user = get_user(request)
    context = {
        "user":  user
    }
    if request.method == 'POST':
            form = ProfilForm(request.POST)
            context = {
                'form': form
            }
            if form.is_valid():
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.email = form.cleaned_data['email']
                user.save()

           
    else:
        form = ProfilForm(initial={'email': user.email, 'first_name' : user.first_name, 'last_name': user.last_name})
        context = {
            'form': form
        }
    return HttpResponse(template.render(context,request))

@decorators.login_required(login_url='/account/login/')
def announces(request):

    template = loader.get_template('accounts/announces.html')
    user = get_user(request)
    context = {
        "announces":  Ad.objects.filter(user_id = user.id)
    }
 
    return HttpResponse(template.render(context,request))

@decorators.login_required(login_url='/account/login/')
def add_announce(request):

    template = loader.get_template('accounts/add.html')
    user = get_user(request)
    announces = Ad()
    context = {
        "announces":  Ad.objects.filter(user_id = user.id)
    }
    if request.method == 'POST':
            form = AnnouncesForm(request.POST)
            
            if form.is_valid():
                announces.title = form.cleaned_data['title']
                announces.description = form.cleaned_data['description']
                announces.category = form.cleaned_data['category']
                announces.type = form.cleaned_data['type']
                announces.status = "online"
                announces.user = user
                announces.save()
                context = {
                    'form': form,
                    'success': True
                }
           
    else:
        form = AnnouncesForm()
        context = {
            'form': form,
            'success': False
        }
    return HttpResponse(template.render(context,request))



def logout_view(request):
    logout(request)
    return redirect('worker:home')

def login_view(request):
    template = loader.get_template('accounts/login.html')
    user = get_user(request)
    if not user.is_authenticated:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            context= {
                'form': form
            }
            if form.is_valid():
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                user = authenticate(email=email, password=password)
                if user:
                    login(request,user,backend='django.contrib.auth.backends.ModelBackend')
                    return redirect('worker:home')
                else:
                    form = LoginForm()
                    context = {
                        'form' : form,
                        "error" : "Vos identifiants sont incorrects !"
                    }
                
        else:
            form = LoginForm()
            context= {
                'form': form
            }
        return HttpResponse(template.render(context,request))

    return redirect('worker:home')

    
@csrf_protect
@requires_csrf_token
def conversation(request, id):
    template = loader.get_template('ad/conversation.html')
    id = int(id)
    print(id)
    conversation = Conversation.objects.get(id=id)
    print(conversation)

    get_messages = Message.objects.filter(conversation_id=id).order_by('-created')
    form = MessageForm()
    message = Message()
    if request.method == 'POST':
        form = MessageForm(request.POST)
        user = get_user(request)
        message.sender = user
        message.conversation = conversation
        message.content = form.data["content"]
        if form.is_valid():
            message.save()
            context = {
                'conversation': conversation,
                'messages': get_messages,
                'form': form,
            }
            return HttpResponse(template.render(context, request))
    context = {
        'conversation': conversation,
        'messages': get_messages,
        'form': form,
    }
   
    return HttpResponse(template.render(context, request))

src/ipssihelp/worker/templates/accounts/add.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

    
        <h2 class="text-center">Ajouter une annonce</h2>

        {% if success %}
            <div class="alert alert-success text-center" role="alert">
                Votre annonces à bien été ajouté !
            </div>
        {% endif %}
        {% if error %}
            <div class="alert alert-danger text-center" role="alert">
                Une erreur est survenue lors de l'ajout
            </div>
        {% endif %}
        <form method="post" class="form-group" id="signup_form">
            {% csrf_token %}
            {% for field in form %}
            <div>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </div>
            {% endfor %}
            
            <button type="submit" class="btn btn-primary mt-3">Ajouter</button>
        </form>
    </div>
{% endblock %}

src/ipssihelp/worker/templates/accounts/announces.html
{% extends "base.html" %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-md-3 ">
                <div class="list-group ">
                    <a href="{% url 'worker:profil' %}" class="list-group-item list-group-item-action">Details</a>
                    <a href="{% url 'worker:announces' %}" class="list-group-item list-group-item-action active">Mes Annonces</a>
                    <a href="#" class="list-group-item list-group-item-action">Mes Messages</a>
                </div> 
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h4>Mes Annonces</h4>
                                <hr>
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                        <th scope="col">Titre</th>
                                        <th scope="col">Descriptions</th>
                                        <th scope="col">Categorie</th>
                                        <th scope="col">Status</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for ad in announces %}
                                        <tr>
                                            <td><a href="{% url 'worker:detail' id=ad.id %}">{{ ad.title }}</a></td>
                                            <td>{{ad.description}}</td>
                                            <td>{{ad.category}}</td>
                                            <td>{{ad.status}}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/ipssihelp/worker/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-center">Connexion</h2>
    {% if error %}
        <div class="alert alert-danger text-center" role="alert">
            {{error}}
        </div>
    {% endif %}
    <div class="container">
        <form method="post" class="form-group" id="signup_form">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Connexion</button>
            </form>
    </div>
    
{% endblock %}

src/ipssihelp/worker/templates/accounts/profil.html
{% extends "base.html" %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-md-3 ">
                <div class="list-group ">
                    <a href="{% url 'worker:profil' %}" class="list-group-item list-group-item-action active">Details</a>
                    <a href="{% url 'worker:announces' %}" class="list-group-item list-group-item-action">Mes Annonces</a>
                    <a href="#" class="list-group-item list-group-item-action">Mes Messages</a>
                </div> 
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h4>Mon Profil</h4>
                                <hr>
                                <table class="table table-bordered">
                                    
                                    <tbody>
                                        <tr>
                                            <th scope="row">Nom</th>
                                            <td>{{user.last_name}}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Prenom</th>
                                            <td>{{user.first_name}}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Email</th>
                                            <td>{{user.email}}</td>
                                        </tr>
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <form method="post" class="form-group">
                                    <h3>Modifier vos informations</h3>
                                    {% csrf_token %}
                                    {% for field in form %}
                                    <div>
                                        {{ field.label_tag }}<br>
                                        {{ field }}
                                        {% if field.help_text %}
                                            <small style="color: grey">{{ field.help_text }}</small>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <p style="color: red">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                    {% endfor %}
                                    <br>
                                    <div class="form-group row">
                                        <button name="submit" type="submit" class="btn btn-primary">Modifier</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/ipssihelp/worker/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
    <h2 class="text-center">Inscription</h2>
    <div class="container">
        <form method="post" class="form-group" id="signup_form">
                {% csrf_token %}
                {% for field in form %}
                <div>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Inscription</button>
            </form>
    </div>
    
{% endblock %}